### ISSUE TITLE
Syntax check fails but works in production

### ISSUE THREAD

**Issue by bastelfreak** [Rackmonkey/puppet-backup#1]
```
$ BUNDLE_PATH=".vendor" bundle 
...
```

```
$ BUNDLE_PATH=".vendor" bundle exec rake syntax --trace
** Invoke syntax (first_time)
** Invoke syntax:check_puppetlabs_spec_helper (first_time)
** Execute syntax:check_puppetlabs_spec_helper
** Invoke syntax:manifests (first_time)
** Execute syntax:manifests
---> syntax:manifests
Could not parse for environment *root*: Could not match |$interface| at /home/bastelfreak/backup/manifests/init.pp:74
rake aborted!

/home/bastelfreak/backup/.vendor/gems/puppet-syntax-2.0.0/lib/puppet-syntax/tasks/puppet-syntax.rb:41:in `block (2 levels) in initialize'
/usr/lib/ruby/2.2.0/rake/task.rb:238:in `call'
/usr/lib/ruby/2.2.0/rake/task.rb:238:in `block in execute'
/usr/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/usr/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/usr/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/usr/lib/ruby/2.2.0/rake/task.rb:201:in `block in invoke_prerequisites'
/usr/lib/ruby/2.2.0/rake/task.rb:199:in `each'
/usr/lib/ruby/2.2.0/rake/task.rb:199:in `invoke_prerequisites'
/usr/lib/ruby/2.2.0/rake/task.rb:178:in `block in invoke_with_call_chain'
/usr/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/usr/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/usr/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/usr/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/usr/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/usr/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/usr/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/usr/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/usr/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/usr/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/usr/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/usr/bin/rake:33:in `<main>'
Tasks: TOP => syntax => syntax:manifests
```

**Comment by bastelfreak** [comment]
After a hint from daenny on #puppet-community I tested the Gemfile and Rakefile from the [puppet-module-skeleton](https://github.com/garethr/puppet-module-skeleton/tree/master/skeleton) which results into this:

```
rake aborted!
NameError: uninitialized constant Syck
/home/bastelfreak/backup/.vendor/gems/puppet-3.8.3/lib/puppet/vendor/safe_yaml/lib/safe_yaml/syck_node_monkeypatch.rb:42:in `<top (required)>'
/home/bastelfreak/backup/.vendor/gems/puppet-3.8.3/lib/puppet/vendor/safe_yaml/lib/safe_yaml.rb:197:in `require'
/home/bastelfreak/backup/.vendor/gems/puppet-3.8.3/lib/puppet/vendor/safe_yaml/lib/safe_yaml.rb:197:in `<module:YAML>'
/home/bastelfreak/backup/.vendor/gems/puppet-3.8.3/lib/puppet/vendor/safe_yaml/lib/safe_yaml.rb:132:in `<top (required)>'
/home/bastelfreak/backup/.vendor/gems/puppet-3.8.3/lib/puppet/vendor/require_vendored.rb:4:in `require'
/home/bastelfreak/backup/.vendor/gems/puppet-3.8.3/lib/puppet/vendor/require_vendored.rb:4:in `<top (required)>'
/home/bastelfreak/backup/.vendor/gems/puppet-3.8.3/lib/puppet/vendor.rb:40:in `require'
/home/bastelfreak/backup/.vendor/gems/puppet-3.8.3/lib/puppet/vendor.rb:40:in `require_libs'
/home/bastelfreak/backup/.vendor/gems/puppet-3.8.3/lib/puppet/vendor.rb:53:in `load_vendored'
/home/bastelfreak/backup/.vendor/gems/puppet-3.8.3/lib/puppet.rb:172:in `<module:Puppet>'
/home/bastelfreak/backup/.vendor/gems/puppet-3.8.3/lib/puppet.rb:29:in `<top (required)>'
/home/bastelfreak/backup/.vendor/gems/puppet-blacksmith-3.3.1/lib/puppet_blacksmith/modulefile.rb:12:in `require'
/home/bastelfreak/backup/.vendor/gems/puppet-blacksmith-3.3.1/lib/puppet_blacksmith/modulefile.rb:12:in `<top (required)>'
/home/bastelfreak/backup/.vendor/gems/puppet-blacksmith-3.3.1/lib/puppet_blacksmith.rb:5:in `require'
/home/bastelfreak/backup/.vendor/gems/puppet-blacksmith-3.3.1/lib/puppet_blacksmith.rb:5:in `<top (required)>'
/home/bastelfreak/backup/.vendor/gems/puppet-blacksmith-3.3.1/lib/puppet_blacksmith/rake_tasks.rb:3:in `require'
/home/bastelfreak/backup/.vendor/gems/puppet-blacksmith-3.3.1/lib/puppet_blacksmith/rake_tasks.rb:3:in `<top (required)>'
/home/bastelfreak/backup/Rakefile:15:in `require'
/home/bastelfreak/backup/Rakefile:15:in `<top (required)>'
/usr/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load'
/usr/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load_rakefile'
/usr/lib/ruby/2.2.0/rake/application.rb:689:in `raw_load_rakefile'
/usr/lib/ruby/2.2.0/rake/application.rb:94:in `block in load_rakefile'
/usr/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/usr/lib/ruby/2.2.0/rake/application.rb:93:in `load_rakefile'
/usr/lib/ruby/2.2.0/rake/application.rb:77:in `block in run'
/usr/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/usr/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/usr/bin/rake:33:in `<main>'
```

**Comment by bastelfreak** [comment]
this was related to a bat combination of ruby (2.2.3p173) and puppet (3.8.3), latest puppet (4.2.2) seems to work better:

```
$ PUPPET_GEM_VERSION="4.2.2" BUNDLE_PATH=".vendor" bundle exec rake syntax
---> syntax:manifests
---> syntax:templates
---> syntax:hiera:yaml
```
